import Head from 'next/head';
import {Header,} from '@/components/Header';
import {Summary} from '@/components/Summary';
import {Experience} from '@/components/Experience';
import {Languages} from '@/components/Languages';
import {Education} from '@/components/Education';
import {TechStacks} from '@/components/TechStacks';
import {Passions} from '@/components/Passions';

const sectionContainer = 'container mx-auto p-6 bg-gradient-to-r from-zinc-100 to-zinc-300 text-zinc-800 border border-zinc-800 rounded-xl b shadow-md shadow-zinc-500 flex flex-col gap-8'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div className='CV w-11/12 mx-auto mt-4'>
          <Header></Header>

          <main className='mt-8'>
            <section className={sectionContainer}>
              <Summary></Summary>
              <Experience></Experience>
              <Languages></Languages>
            </section>

            <section>
              <Education></Education>
            </section>

            <section>
              <TechStacks></TechStacks>
            </section>

            <section>
              <Passions></Passions>
            </section>
          </main>

        </div>
    </>
  );
}
